[profile.default]
src = 'contracts'
out = 'generated/artifacts_forge'
libs = ['node_modules', 'lib']
test = 'tests'
cache_path  = 'generated/cache_forge'

[doc]
homepage= "HOME.md"
ignore = [
    "*/EAS/*.sol",
    "*/mock/*.sol",

    "*/LendNestV0Storage.sol",
    "*/ProtocolFeeMock.sol",
    "*/LendNestV2Mock.sol",

    "*/libraries/*.*",
    "*/types/*.*",
    "*/Types/*.*",
    "*/interfaces/*.*",
    "*/interfaces/escrow/*.*", 
    "*/README.md",
]